spring:
  datasource:
    url: jdbc:mysql://trav0027.ddns.net:3306/webnotes?serverTimezone=UTC
    username: monty
    password: password
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect